spring.application.name=mini-erp
server.port=${PORT:8080}

# ===============================
# DATABASE (Railway PostgreSQL)
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# IMPORTANTE para Railway (evita errores SSL)
spring.datasource.hikari.maximum-pool-size=5

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# INICIALIZACIÓN
# ===============================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ===============================
# JWT
# ===============================
app.jwt.secret=${JWT_SECRET:super-secreto-super-secreto-super-secreto-1234567890}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ===============================
# JSON
# ===============================
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false